### ISSUE TITLE
Failure to authenticate with Yubikey FIDO2 SSH key

### ISSUE THREAD

**Issue by d4hines** [Pilou97/yggit#35]
When running yggit (on my dev branch) I get the following error after correctly entering my pin and touching my Yubikey:

```
cargo run -- push           
   Compiling yggit v0.0.1 (/home/d4hines/repos/yggit)
    Finished dev [unoptimized + debuginfo] target(s) in 0.73s
     Running `target/debug/yggit push`
Setting branch d4hines/more-characters to commit 3c12c3313056fd57fde672ae1076d8adc2b59815
Setting branch d4hines/nix to commit 0fc6732a9cce20673d2d64b00a5497ff86caee09
thread 'main' panicked at src/git/git.rs:143:14:
fetch repository has fialed: Error { code: -1, klass: 0, message: "all authentication attempts failed" }
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: core::result::Result<T,E>::expect
             at /build/rustc-1.75.0-src/library/core/src/result.rs:1034:23
   4: yggit::git::git::Git::find_remote_head
             at ./src/git/git.rs:136:9
   5: yggit::core::push_from_notes
             at ./src/core.rs:88:29
   6: yggit::commands::push::Push::execute
             at ./src/commands/push.rs:42:9
   7: yggit::main
             at ./src/main.rs:34:33
   8: core::ops::function::FnOnce::call_once
             at /build/rustc-1.75.0-src/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

The ssh-agent is definitely prompting the Yubikey, but it looks like Yggit is somehow not properly looking for the response.

**Comment by d4hines** [comment]
(FWIW this is no longer a blocker for me - I switched back to PGP-based keys anyway since I was having trouble with preserving the no-touch-required option with resident keys. Typing in my pin and touching the key every few minutes was getting annoying).
